#!/usr/bin/env php
<?php

require_once __DIR__ . "/../../../vendor/autoload.php";

use Controllers\RaceController;
use Views\View;

$input = $_SERVER['argv'];

$race = new RaceController();

if (isset($input[1])) {
    $race->overtake($input[1]);
    exit;
}
View::errorMessageOvertakeNull();
