#!/usr/bin/env php
<?php

require_once __DIR__ . "/../../../vendor/autoload.php";

use Views\View;

$input = $_SERVER['argv'];

if (!empty($input[1])) {
    switch ($input[1]) {
        case 'adicionarCarro':
            View::descNewCar();
            break;

        case 'definirPosicoes':
            View::descSetPosition();
            break;

        case 'exibirCarros':
            View::descShowCars();
            break;

        case 'iniciarCorrida':
            View::descStartRace();
            break;

        case 'finalizarCorrida':
            View::descFinishRace();
            break;

        case 'ultrapassar':
            View::descOvertake();
            break;

        case 'relatorioUltrapassagens':
            View::descReport();
            break;

        case 'excluirCarro':
            View::descDeleteCar();
            break;

        default:
            View::errorMessageCommands();
            break;
    }
} else {
    View::defaultMessageCommands();
}
