#!/usr/bin/env php
<?php

//preg_match('/^--([\w-]+)(?:=(.*))?$/', $param, $matches);

use Controllers\Car;

$result = $_SERVER['argv'];

$car = new Car();

$car->newCar($result[1], $result[2], $result[3], $result[4], $result[5]);
