#!/usr/bin/env php
<?php

use Api\Builders\TerminalCommandBuilder;
use Api\Messages\TerminalMessages;
use Api\Services\CommandExecutorService;

require_once __DIR__ . "/vendor/autoload.php";
require_once __DIR__ . "/config/env.php";

try {
    $command = (new TerminalCommandBuilder($argv))->getCommand();
    $response = (new CommandExecutorService())->run($command);

    TerminalMessages::successMessage($response->getMessage());
} catch (Exception $exception) {
    TerminalMessages::errorMessage($exception->getMessage());
}
