#!/usr/bin/env php
<?php

require_once __DIR__ . "/vendor/autoload.php";

use Api\Messages\CommandMessages;
use Api\Messages\View;

$input = $_SERVER['argv'];

if (!empty($input[1])) {
    switch ($input[1]) {
        case 'adicionarCarro':
            CommandMessages::descNewCar();
            break;

        case 'definirPosicoes':
            CommandMessages::descSetPosition();
            break;

        case 'exibirCarros':
            CommandMessages::descShowCars();
            break;

        case 'iniciarCorrida':
            CommandMessages::descStartRace();
            break;

        case 'finalizarCorrida':
            CommandMessages::descFinishRace();
            break;

        case 'ultrapassar':
            CommandMessages::descOvertake();
            break;

        case 'relatorioUltrapassagens':
            CommandMessages::descReport();
            break;

        case 'excluirCarro':
            CommandMessages::descDeleteCar();
            break;

        default:
            echo CommandMessages::errorMessage_CommandNotFound();
            break;
    }
} else {
    CommandMessages::defaultMessageCommands();
}
