#!/usr/bin/env php
<?php

require_once __DIR__ . "/../vendor/autoload.php";

use Controllers\CarController;
use View\View;

$input = $_SERVER['argv'];

for ($i = 1; $i <= 5; $i++) {
    if (!isset ($input[$i])) {
        View::errorMessageNewCar();
        exit;
    }
}

if (!empty($input[6])) {
    View::errorMessageParameters();
    exit;
}

if (!is_int($input[5]) || $input[5] < 0) {
    View::errorMessageNotInteger();
    exit;
}

$car = new CarController();
$car->newCar($input[1], $input[2], $input[3], $input[4], $input[5]);
