#!/usr/bin/env php
<?php

require_once __DIR__ . "/../vendor/autoload.php";

use Controllers\ControllerCar;

$result = $_SERVER['argv'];

for ($i = 1; $i <= 5; $i++) {
    if (!isset ($result[$i])) {
        echo "Adicione todas as informacoes para adicionar um carro" . PHP_EOL . PHP_EOL
        . "comando: adicionarCarros Piloto Marca Modelo Cor Ano" . PHP_EOL . PHP_EOL;
        exit;
    }
}

$car = new ControllerCar();
$car->newCar($result[1], $result[2], $result[3], $result[4], $result[5]);
