#!/usr/bin/env php
<?php

require_once __DIR__ . "/../../../var/www/html/vendor/autoload.php";

use Controllers\ControllerCar;
use View\View;

$input = $_SERVER['argv'];

for ($i = 1; $i <= 5; $i++) {
    if (!isset ($input[$i])) {
        View::errorMessageNewCar();
        exit;
    }
}

$car = new ControllerCar();
$car->newCar($input[1], $input[2], $input[3], $input[4], $input[5]);
