#!/usr/bin/env php
<?php

require_once __DIR__ . "/../../../var/www/html/vendor/autoload.php";

use Controllers\ControllerCar;
use View\View;

$result = $_SERVER['argv'];

if(empty($result[1])) {
    View::errorMessageDeleteCar();
    exit;
}

$car = new ControllerCar();
$car->deleteCar($result[1]);
