#!/usr/bin/env php
<?php

require_once __DIR__ . "/../vendor/autoload.php";

use Controllers\ControllerCar;
use View\View;

$input = $_SERVER['argv'];

$car = new ControllerCar();
$car->deleteCar($input[1]);
