#!/usr/bin/env php
<?php

require_once __DIR__ . "/../../../var/www/html/vendor/autoload.php";

use Lib\JSON;
use View\View;

$input = $_SERVER['argv'];

$true = [
    'Status' => true
];

$false = [
    'Status' => false
];

$godMode = JSON::getGodMode();

$password = '81dc9bdb52d04dc20036dbd8313ed055';

if (md5($input[1]) === $password && $godMode['Status'] == 0) {
    JSON::setJson('godMode', $true);
    View::messageGodModeOn();
    exit;
}

if (md5($input[1]) === $password && $godMode['Status'] == 1) {
    JSON::setJson('godMode', $false);
    View::messageGodModeOff();
    exit;
}

View::errorMessageInvalidPassword();
