#!/usr/bin/env php
<?php

require_once __DIR__ . "/../../../var/www/html/vendor/autoload.php";

use Controllers\ControllerRace;
use View\View;

$input = $_SERVER['argv'];

$race = new ControllerRace();

if(isset($input[1])) {
    $race->overtake($input[1]);
} else {
    View::errorMessageOvertakeNull();
}
