#!/usr/bin/env php
<?php

require_once __DIR__ . "/../vendor/autoload.php";

use Controllers\ControllerRace;
use View\View;

$result = $_SERVER['argv'];

$race = new ControllerRace();

if(isset($result[1])) {
    $race->overtake($result[1]);
} else {
    View::errorMessageOvertakeNull();
}
