#!/usr/bin/env php
<?php

require_once __DIR__ . "/../../../var/www/html/vendor/autoload.php";

use View\View;

$result = $_SERVER['argv'];

if (!empty($result[1])) {
    switch ($result[1]) {
        case 'adicionarCarros':
            View::descNewCar();
            break;

        case 'definirPosicoes':
            View::descSetPosition();
            break;

        case 'exibirCarros':
            View::descShowCars();
            break;

        case 'iniciarCorrida':
            View::descStartRace();
            break;

        case 'finalizarCorrida':
            View::descFinishRace();
            break;

        case 'ultrapassar':
            View::descOvertake();
            break;

        case 'relatorioUltrapassagens':
            View::descReport();
            break;
        default:
            View::errorMessageCommands();
    }
} else {
    View::defaultMessageCommands();
}


